version: '3'

services:
  db:
    image: mongo:5.0
    container_name: mongodb
    ports: 
      - 27017:27017
    restart: always
    environment: 
      MONGO_INITDB_DATABASE:  api-challenge 
      MONGO_INITDB_ROOT_USERNAME: api-challenge
      MONGO_INITDB_ROOT_PASSWORD: api-challenge
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js

